version: '3.8'

services:
  python:
    build: .
    container_name: ${BOT_NAME}_app
    restart: always
    ports:
      - "8001:8000"
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "critical"]
    networks:
      - dtmtestbot

  postgres:
    image: postgres:17
    container_name: ${BOT_NAME}_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - dtmtestbot

  redis:
    image: redis:latest
    container_name: ${BOT_NAME}_redis
    restart: always
    command: >
      sh -c "redis-server --maxclients 10000 && redis-server --save --appendonly yes"
    sysctls:
      - net.core.somaxconn=65535
    volumes:
      - redis:/data
    networks:
      - dtmtestbot

volumes:
  database:
  redis:
    driver: local

networks:
  dtmtestbot:
    driver: bridge
